name: 'SHA Sentry'
description: 'Scan and report unpinned GitHub Actions in workflow files with SHA recommendations'
author: 'SHA Sentry Action'
branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github_token:
    description: 'GitHub token for API access to resolve action SHAs'
    required: true
    default: ${{ github.token }}
  
  exclude_patterns:
    description: 'Comma-separated list of file patterns to exclude from scanning'
    required: false
    default: ''

outputs:
  files_scanned:
    description: 'Number of workflow files that were scanned'
    value: ${{ steps.sha_scan.outputs.files_scanned }}
  
  total_actions:
    description: 'Total number of actions found across all files'
    value: ${{ steps.sha_scan.outputs.total_actions }}
  
  unpinned_actions_found:
    description: 'Number of unpinned actions that need SHA pinning'
    value: ${{ steps.sha_scan.outputs.unpinned_actions_found }}
  
  findings:
    description: 'JSON array of detailed findings with SHA recommendations'
    value: ${{ steps.sha_scan.outputs.findings }}

runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
      with:
        node-version: '20'
    
    - name: Install dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm ci --only=production
    
    - name: Run SHA Sentry Scanner
      id: sha_scan
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
        EXCLUDE_PATTERNS: ${{ inputs.exclude_patterns }}
      run: node ${{ github.action_path }}/src/index.js